(async function ZCD_Google_BatchRunner_SameTab() {
  /******************************************************************
   * Run this from https://www.google.com/ (same-origin requirement)
   * Chrome-safe SAME-TAB version (no popups)
   ******************************************************************/

  // ---------- UI PROGRESS ----------
  function updateProgress(done, total, currentUrl = "", note = "") {
    const pct = total ? Math.floor((done / total) * 100) : 0;
    const barSize = 30;
    const filled = Math.floor((pct / 100) * barSize);
    const bar = "█".repeat(filled) + "░".repeat(barSize - filled);
    console.clear();
    console.log(`Zocdoc link collector (${done}/${total})`);
    console.log(`[${bar}] ${pct}%`);
    if (currentUrl) console.log(`Current: ${currentUrl}`);
    if (note) console.log(note);
  }

  // ---------- HELPERS ----------
  const wait = (ms) => new Promise((res) => setTimeout(res, ms));

  function safeParseGoogleResultUrl(href, base = "https://www.google.com") {
    try {
      if (href.startsWith("/")) href = base + href;
      const u = new URL(href);
      if (u.pathname === "/url" && u.searchParams.get("q")) {
        return u.searchParams.get("q");
      }
      if (u.protocol === "http:" || u.protocol === "https:") return u.href;
    } catch {}
    return null;
  }

  function extractLinksFromSerpDocument(doc, siteMustInclude) {
    const root = doc.querySelector("#search") || doc;
    const anchors = Array.from(root.querySelectorAll("a[href]"));

    const out = [];
    for (const a of anchors) {
      const raw = a.getAttribute("href") || "";
      const resolved = safeParseGoogleResultUrl(raw);
      if (!resolved) continue;
      if (resolved.includes(siteMustInclude)) {
        out.push(resolved.split("#")[0]);
      }
    }
    return Array.from(new Set(out));
  }

  function looksBlockedOrConsent(doc) {
    const text = (doc.body?.innerText || "").toLowerCase();
    const title = (doc.title || "").toLowerCase();
    const signals = [
      "before you continue",
      "consent",
      "unusual traffic",
      "sorry",
      "not a robot",
      "detected unusual traffic",
      "captcha",
      "verify"
    ];
    return signals.some((s) => title.includes(s) || text.includes(s));
  }

  // ---------- CONFIG ----------
  const SITE = "www.zocdoc.com";
  const QUERY_TEMPLATE = (raw) => `site:${SITE} ${raw}`;
  const RESULTS_PER_PAGE = 20;
  const BATCH_SIZE = 20;
  const DELAY_BETWEEN_QUERIES_MS = 1500;
  const PAGE_LOAD_WAIT_MS = 3500;

  // ---------- INPUT NAMES ----------
  const namesText = `
ALEX CAPACE
LISA BOSCO
SAURAV CHATTERJEE
MAUREEN HOGAN
SOO KWON
JASON SONG
WAYLAND WU
YIMING YANG
CHRISTOPHER HARTMAN
JOHN AFTHINOS
JEE SHIM
JONATHAN PARAMO
MICHAEL MANOLIOS
DAVID WITKES
RANDALL GOULD
JENNY PANG-WOO
VARUN THAPAR
CRYSTAL MCGEOWN
MELISSA CLIFFORD
DAVID FRIEDMAN
DAVID MAJURE
LISSA SUGENG
IRA NASH
JASJIT BHINDER
KATHLEEN DAVIDSON
DIPAN UPPAL
BETH HEYDEMANN
SALINA THAPA
MELISSA FACKLER
LINDSEY MCPHILLIPS
ELENA KWON
CRAIG GROSS
MELISSA CHU LAM
BRIAN STRIZIK
RAJAT GOYAL
DESIREE DENNIS
SAMY SELIM
DONNA CHELLE MORALES
MAHMOUD BOKHARI
NEIMAN RAMJATTAN
SAMANTHA AMENDOLA
JESSE EISENBERG
VANDY FERRER
DONNA KALENDERIAN
JAGDEEP SINGH
MOHIT SHARMA
TARA MANN
THERESA NICOSIA
ASMA KHALIQ
KATERINA SAFONOVA
RACHEL NAHRWOLD
ANJORI DUNBAR
SATJIT BHUSRI
MARRICK KUKIN
JILL KALMAN
AKILA VENKATARAMAN
NEIL COPLAN
CARL REIMERS
BABAK HASSID
ANDREA MIGNATTI
AKSHAI BHANDARY
ERIN MACKINNON
HAROUT YACOUB
DILIA ADASKIN
MARINA POPOVA
MARCIN KUZMA
LUIGI PIRELLI
OSAMA HADDAD
ZACHARY KON
TERRI BOOTH
SYED HUSSAIN
NEHA REDDY
IOSIF GULKAROV
BYRON PATTON
JONATHAN HEMLI
STEPHANIE ORTIZ
KRISTINE SCOTT
ALLISON FAYANS
DAVID HIRSCH
JOSHUA SEGAL
THERESA FAN
HUNTER MARTIN
MONAL PATEL
JILLIAN GRANT
LAURENT GANRY
YAEL ADHAMI
JOANA FORSEA
KATHLEEN SCHULTZ
SIMONE REISMAN
ANUKRITI GUPTA
JACQUELINE MINASSO
RESHMI KAPOOR
NOAH LEVIT
KALEE SHAH
SARAH AHMED
MARY VALINOTTI
JESSICA NEWBURGER
KELLY WEINER
MARINA YUSUPOV
KAREN WILSON
ANSLEY ROCHE
GRIFFIN BAUM
TASHI WANGYAL
ELIZABETH ANISIS
SAMUEL QUINTERO
YASMIN MOHAMED
SANDY BAWUAH
ARPITA BHALODKAR
JACQUELINE GOLDEN
GABRIELLA ROMEO
THERESA WALSH
EKAMBARAM ILAMATHI
DINESH KUMAR KANNABHIRAN
ALAN VAZQUEZ ESCALANTE
SARA DEVANY
ELAIN WU
ANNA MARIA CAGNINA-REILLY
ASHLEY SAKOWITZ
PATRICIA MUSTO
MONA RECHNER
KEVIN DOLLEY
SUNANDA MANGRAJ
IRENE GALPERIN
PRIYANKA MAKKAR
ANA HALLINAN
LUBAINA PRESSWALA
ESTI CHARLAP
ALYSON MYERS
TARA KIM
SUSHMITHA ECHT
SUSHIL SHARMA
MALY TIEV
SHIVI SIVA
CALLEY LEVINE
SHEELAMMA THOMAS
TARAYN DHANSEW
IRA ROSENBLUM
MARIA ANTON
LINKE MA
SANJIV SHARMA
NINA KELLO
CAROL CAICO
MELISSA KESLAR
RAVI VASWANI
CHRISTINA PENTLOW
TATIANA PORTELA
RUMENA KABIR
YEE-MING CHEUNG
MASHAL DURRANI
ADRIANA ABRUDESCU
HATEF MASSOUMI
BEN DA
JINTU JOHNSON
ELISHIA CRUMWELL-MACK
LAWRENCE HA
NICOLE PARSONS
THOMAS CHEN
DARRIN LONDON
NEHA PARALKAR
REBECCA SHAFER
EUGENIA LUO
AISHA KHAN
SHREYA SUBRAMANIAM
SAMANTHA BACA
PRISCILLA PERSAUD
HALYNA CHYKYDA
LILIYA SEMENOVA
STEPHANIE WANLASS
VARVARA BORYUSHKINA
IRYNA ILYASOVA
MELISSA LIEBOLD
AMANDA PERSAUD
RICHARD HWANG
FNU VARSHA
JOSEPH IDA
NEERAJ ANAND
RICHA BHARDWAJ
SHAMAYL AHMED
STEPHANIE PORTER
ARADIA FU
DAVID SEYBURN
MANEET KAUR-KOHLI
EILEEN WALSH
IMNETT HABTES
DANIELA OLIVERA-PARENTE
YAQOOT KHAN
STEVEN FEINSILVER
AREZOO SAHIHOLAMAL
SAMI SABA
LAURA FITZPATRICK
POOJA NARWAL
SALMAN KHAN
GEORGE PILIGIAN
VALERIE BARTA
SHERVIN SHADIANLOO
JAYME TAYLOR
EVA MARDONES
JONATHAN THALER
TINA DOBSEVAGE
SONYA SHAH
HILLEL HAMMERMAN
MARTINA MURPHY
MIKE GORENCHTEIN
ERIK ANDERSON
HAYLEY WORLEDGE
MARIO ALICANDRI
STEPHEN MULROONEY
GLORIA LAN
CATALINA CINCU
MARIANNA VYNNYK
VIVIAN ASAKOMA
SUNITHA KORAPATI
JOHNNY TRUONG
DANNY NGUYEN
ANDREA ISAACS
KIMBERLY JOSEPH-PERSAUD
DAVID WEINTRAUB
TANYA KAPOOR-MAINI
NICHOLE LOPEZ
CATHERINE CLARO
DEBORAH RISBROOK
RICHARD LEUNG
EMMA KAYE
JOHN ANNESSA
SUNANDA NANDURI
TATYANA GITLEVICH
MARIAM MASRI
DAWN PARKER
AHMAD LATEFI
DESTINY SEAY
NICOLE SALANT
KEVIN SHAH
JESSICA THEMAK
RAFAEL ORTIZ
BRITTANY RING
MARIA DEDIOS
AMY MCKEOWN
MELISSA PHIPPS
JULIA RABER
JOANNA DALTON AYOUNG
KELSEY KREDENTSER
ANGELO GARRIDO
ROSIBEL HERNANDEZ CASTRO
KATHLEEN CSILLAG-KLEIN
STACY DANIEL
KERRY O'BRIEN- ESPINOZA
SUSAN NOLL
LINDSAY PRICE
MICHELE MAYER
LAURA JABBOUR
ELIZABETH MORRISON
NATHALIE SEJOUR
MASSIEL OYANGUREN
PATRICIA HONASKI
EFIGENIA NUNEZ
AMIR SHAY
CAMILLE RICCIARDI
REBEKA RACZ
RISA KLEIN
ARIELLA NOURIEL
ALEXANDRA BLACK
KATHY-JO GABBUR
NICOLE LAMPRINAKOS
LORRAINE LAMM
STEFANIE FERRARO
LILLY SINGH
LINDA BAHOUTH
ANA ESCOBAR-BOTERO
SYDNEY CHANG
SUSAN MAXWELL
AMANDA YASSIN
JACQUELINE GUTERMAN
KATHRYN VIGGIANI
ANTONIO PULLANO
MARIA CHOPIVSKY
JENNIFER LAU
DIANA CHEREZOVA
MARIANNE DRAGO
JOANNA RHODES
JASDEEP SANDHU
DENA MATHEW
SUNHEE KIM
MARINA ANOSOV
LAKSHMI RAJDEV
JULIA SCHAEFER-CUTILLO
AUDREY PENDLETON
CHERYL MENSAH
HEATHER KATZ
SUSAN BADER
NANA ABRAMS
PRACHI DUA
RASHMI VERMA
STEPHEN OBSTBAUM
CESAR MICHAEL SAMSON
WILLIAM LORUSSO
JEFFREY OKADA
JESSICA INTRAVIA
STEVEN ALESSI
TARA VANDERBURG
DONNA ROMANO
SOHRAB VIRK
XUAN QIU
CHARYTIN MARESCO
LISA HORVATH
ASHLEY BURLAGE
ERICA PACIFICO
DIANNE SCIMECA
TING TING BRENNER
DANIEL SEIDMAN
CAROLINE SUTTLE
RICHARD LOPEZ
JACOB CZAJKA
MUZNAY KHAWAJA
GRACE SUPPA
MANISH MAMMEN
NATASHA MENDEZ
KATHERINE STEIGERWALD
MARIA NARINE
MARIA BERNSTEIN
DOROTHY MOLLOY
SHAMIM LALANI
NANCY ALFIERI
HAE-RI SONG
YAEL EISENBERG
AHUVA EDELSTEIN
YAA ASANTE
DIANA XIAO BING LI
GERI GALOTTI
KERRIANN LATTEN
ASHLEY MARTIN
OLIVE PLHAK
ALVIE AHSAN
FREDERIC KALENSCHER
PUNITA PONDA
IDIL EZHUTHACHAN
YASMIN HAMZAVI ABEDI
ANDRE REBAZA
ZEYNEP KUCUK
STEFAN HAGMANN
SAVERIO CIANCIOTTA
DAVID HYMAN
MARTIN BIALER
PEYMAN BIZARGITY
LAURA PISANI
JOAN VILLACASIO
GABRIELLE AMOROSO
SUSAN MCCARTHY
LAWRENCE FINK
KAREN BRIDE
POOJA DESAI
VIVIANA VIDAL ANAYA
JACQUELINE GAMBESKI
JANNIKA DODGE KHATAMI
CHRISTOPHER MINOR
FRANCINE BLEI
CHALESE RICHARDSON-OLIVIER
MARISSA MCCAY
JANE MCSWEENEY
STEVEN THAU
FARRAH GUTWEIN
HENNESSY SKEHAN
DANA PROTOMASTRO
JUSTEN MOLINA
ERIC LEUNG
LORETTA WONG
NORA MAY CROTTY
KRYSTAL LEE
NEEL CHANDEL
PHILIP MELCHIORRE
SEWIT TECKIE
ADEKEMI EGUNSOLA
BOGUM KWON
MICHAEL KUNCEWITCH
SHAWNA MOSCOWITZ
TORI GUARDINO
JACLYN NELSON
FIRAS MUSSA
MATTHEW GIANGOLA
DIANA SAMBUCO
MARIA DIFIORE
JULIA ALISHAYEV
PETER LEE
CICI ZHANG
SHAWNEE LI-A-PING
KELECHI AKUMA
PATRICIA MACDONALD
KOJO WALLACE
KELLI SUMMERS
NICOLE PESCE
DEBORAH ALLIS
ALLAN CONWAY
KHALIL QATO
MARTA SHEREMETA
JONATHAN DEITCH
KIMLYN LONG
DAVID BERLER
SHABANA PERVEEN
JULIA PIERRE-LOUIS
HAFSA MEMON
EMILY SCHWERTL
NOEL ARMENAKAS
JONATHAN NIETES
KATHLEEN MURPHY
BRENAINN FLANAGAN
CLAIRE POPPLEWELL
EUN JI KIM
DENNIS FEIHEL
THOMAS GUT
GARBIS DABAGHIAN
ANNA CORNISH
SHADWA HASSAN
MARIO CASTELLANOS
AYAH AHAMED
ANDREW ATHANASSIOU
AMY SHARMA
GEORGE RAPTIS
MONIQUE HARTLEY-BROWN
NABEELA PATAIL
CHRYSTAL LANDRY
SHIRIN ATTARIAN
JEAN LEE
JENNIFER PARK
ELENA PALAU
LAURA AMBROSIO
KAREN GRAUER
EVA MCLOUGHLIN
SONIYA MATHAI
ALEXIS DEMOPOULOS
LOUISE PURCELL
RIYA PATEL
NIKITA ROY
SARA ALOTHMAN
AMY GALGANO
ABBE NADEL
MICHELE IACOVIELLO
JEFFREY CHI
ELIZABETH CONNELLY
BLANCHE KUBIK
JIA LLON YEE
KALA MATHEW
CHRISTOPHER GEORGE
MILENA VUKELIC
KRYSTINA TONGSON
ASHWIN RANGAVAJJULA
JOSELYN BAEZ
MOHAMMAD MOUSSAVI
ARMIN MAGHSOUDLOU
MANDY XI
KRISTINA BASILE
CHELSEA YAGER
WYNN HTUN
SOPHIA HU
MARIE CASTRONOVO
JOSEPHINE TRAMUTOLA
SHELBY REICH
QUSAI HAMMOURI
KATHRYN BAXTER
CRISTINA DORAN
JENNIFER SILVEY
KAREN GIBBS
ASAF GAVE
GALINA GLINIK
SAMUEL HAWKINS
LISA SHIMOTAKE
CHRISTINA OLIVIERI
FRANK DIROMA
MEGAN WALSH
AKOSUA CHILDS
TELMO SANTOS
SHENEZAH RASHEED
YEHUDA SHAPIR
ARUSHI DHAR
DENISE HAYES
CRISTINA FARRELL
SIMONE JHAVERI
BRITTANY WISE-ORINGER
LAURA MUNOZ
DENNIS BESONG
CHRISTOPHER FECEK
NICOLE MARKY
DANIEL SHAPIRO
JUDITH MAGLOCZKI
STEPHANIE WEST
NIMA FLORIO
EMILY SAWYER
MARK CREIGHTON
ASHANTI FRANKLIN
LILY NAZ SHAMSNIA
ESTHER WEITZNER
STEPHANIE GRUBE
KYRA FORTE
LOVLEEN SINGH
DAVID KADOSH
CHRISTOPHER AWWAD
LEYLA EDWARDS
SAFIYA RICHARDSON
SARA GUEVARA
ALYSSA HARPER
LORI HUTCHINSON
CYNARA COOMER
SARA KIM
AGNES LASEINDE
PEGGY ESTIME MARGETSON
MELINDA ANAMDI
FRANK SCHIRRIPA
ROBERT BARTOLOMEO
JOANNA SANZONE
ELISHEVA ROSENFELD
INGRID DESROCHES
YONATAN HILLMAN
JOSEPH MACKEY
JEFFREY ZIMERING
FARHANA JUI
LAURA ANDRESKI
MATTHEW DENG
DANIEL WOLLOCH
KAREN BROWNER-ELHANAN
MIRANDA ROSENBERG
ANNE HABER
AHMED GEMEI
SNEHA SHRIVASTAVA
MICHAEL KHALILI
TATIANA NDJATOU
JOHN SOTTILE
MICHELLE EVANGELIST
INA TERON-MOLINA
ANDREW WEBER
AHMAD JAVED
PA PAULINA COLLIER, LLC
HOOSNA HAQUE
KATLYN ANTHONY
RAMONA RAJAPAKSE
KARINA FATAKHOVA
ZARLASHT KHAN
MUBDIUL ALI
CHRISTINE NWAISER
LISA PEREIRA
CRISTINA BERNADIN

`.trim();

  const names = namesText
    .split(/\r?\n/)
    .map((s) => s.trim())
    .filter(Boolean);

  if (!names.length) {
    console.warn("No names found.");
    return;
  }

  // ---------- STATE ----------
  const STATE_KEY = "ZCD_COLLECTOR_STATE_SAMETAB_V1";
  const saved = JSON.parse(localStorage.getItem(STATE_KEY) || "{}");

  let startIndex = Number.isFinite(saved.startIndex) ? saved.startIndex : 0;
  let allLinks = new Set(saved.allLinks || []);
  let perNameCounts = saved.perNameCounts || {};

  const runnerUrl = location.href;
  const endIndex = Math.min(startIndex + BATCH_SIZE, names.length);

  updateProgress(startIndex, names.length, "", `Starting batch ${startIndex} → ${endIndex - 1}`);

  // ---------- RUN ----------
  for (let i = startIndex; i < endIndex; i++) {
    const name = names[i];
    const query = QUERY_TEMPLATE(name);

    const googleUrl =
      "https://www.google.com/search?q=" +
      encodeURIComponent(query) +
      `&num=${RESULTS_PER_PAGE}&hl=en&gl=us&pws=0`;

    updateProgress(i, names.length, googleUrl, `Searching: ${name}`);

    // Navigate same tab
    location.href = googleUrl;
    await wait(PAGE_LOAD_WAIT_MS);

    const doc = document;

    if (looksBlockedOrConsent(doc)) {
      updateProgress(i, names.length, googleUrl, "⚠️ Block / consent detected. Solve manually, then rerun.");
      break;
    }

    const linksForThisName = extractLinksFromSerpDocument(doc, SITE);
    linksForThisName.forEach((l) => allLinks.add(l));
    perNameCounts[name] = linksForThisName.length;

    // Save state
    localStorage.setItem(
      STATE_KEY,
      JSON.stringify({
        startIndex: i + 1,
        allLinks: [...allLinks],
        perNameCounts
      })
    );

    // Return to runner
    history.replaceState(null, "", runnerUrl);
    await wait(500);

    updateProgress(
      i + 1,
      names.length,
      "",
      `Done: ${name} | Links: ${linksForThisName.length} | Total: ${allLinks.size}`
    );

    if (DELAY_BETWEEN_QUERIES_MS) await wait(DELAY_BETWEEN_QUERIES_MS);
  }

  // ---------- EXPORT ----------
  const csv = [...allLinks].join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = `zocdoc_links_unique_${allLinks.size}.csv`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);

  updateProgress(endIndex, names.length, "", `✅ Finished. Exported ${allLinks.size} unique links.`);
})();
